ServerName localhost
<VirtualHost *:80>
    ServerAdmin webmaster@localhost


    # Path to your Django app inside the container
    WSGIDaemonProcess ecommerce python-path=/app python-home=/app/venv
    WSGIProcessGroup ecommerce

    # Entry point for the WSGI application
    WSGIScriptAlias / /app/ecommerce/wsgi.py

    <Directory /app/ecommerce>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    # Static files
    Alias /static/ /app/static/
    <Directory /app/static>
        Require all granted
    </Directory>

    # Media files
    Alias /media/ /app/media/
    <Directory /app/media>
        Require all granted
    </Directory>

    # Logs
    ErrorLog /var/log/apache2/error.log
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>