# Generated by Django 5.1.6 on 2025-03-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1920x1080 pixels', upload_to='banners/'),
        ),
    ]
